version: '3'

services:
  dev:
    build: .
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - '3000:3000'
    env_file: .env
    command: sh -c "yarn && yarn dev"
